[package]
name = "ecdsa"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
secp256k1 = "0.30.0"
sha2 = "0.10"
nalgebra = "0.33.2"
rug = "1.16"  # Pour les grands entiers et calculs modulaires
